### ISSUE TITLE
Can't compile on OS X 10.8.2

### ISSUE THREAD

**Issue by JS210** [openyou/emokit#65]
Hi,

I followed the instructions in the readme, installed everything that needed to be installed. Then downloaded the emokit-master, ran "cmake ." and "make", no problems.

I then used cmake/make, no problems. Then tried to compile the emokitd.c using gcc and received the following error:

emokitd.c:12:27: error: emokit/emokit.h: No such file or directory
emokitd.c: In function ‘main’:
emokitd.c:19: warning: assignment makes pointer from integer without a cast
emokitd.c:20: error: ‘EMOKIT_VID’ undeclared (first use in this function)
emokitd.c:20: error: (Each undeclared identifier is reported only once
emokitd.c:20: error: for each function it appears in.)
emokitd.c:20: error: ‘EMOKIT_PID’ undeclared (first use in this function)
emokitd.c:34: error: storage size of ‘c’ isn’t known

I then changed the path in the include linking emokit.h (added "../../"), tried to compile again and received:

Undefined symbols for architecture x86_64:
  "_emokit_create", referenced from:
      _main in ccPtrAz4.o
  "_emokit_get_count", referenced from:
      _main in ccPtrAz4.o
  "_emokit_get_next_frame", referenced from:
      _main in ccPtrAz4.o
  "_emokit_open", referenced from:
      _main in ccPtrAz4.o
  "_emokit_read_data", referenced from:
      _main in ccPtrAz4.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status

As well as the following error when running 'make' again:
Linking C executable emokitd
ld: library not found for -lemokit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [emokitd] Error 1
make[1]: **\* [CMakeFiles/emokitd.dir/all] Error 2
make: **\* [all] Error 2

I get the same error regardless of compiling in different architetures?

Has anybody got an idea what I'm doing wrong? Or is this a well known issue I'm unaware of?

Thanks
