### ISSUE TITLE
Can't get emokit to work on Ubuntu 13.04 Device: 1234:ed02

### ISSUE THREAD

**Issue by guysoft** [openyou/emokit#94]
Hello,
I compiled emokit and ran ``emokitd`` which returns no output, it just runs and exists.

When I try executing example.py I get:

    Traceback (most recent call last):
      File "/home/guy/bci/local/lib/python2.7/site-packages/gevent/greenlet.py", line     390, in run
        result = self._run(*self.args, **self.kwargs)
      File "/home/guy/workspace/bci/emokit/python/emokit/emotiv.py", line 353, in setup
        self.setupPosix()
      File "/home/guy/workspace/bci/emokit/python/emokit/emotiv.py", line 452, in setupPosix
        self.serialNum = setup[0]
    TypeError: 'NoneType' object has no attribute '__getitem__'
    <Greenlet at 0x10917d0: <bound method Emotiv.setup of <emokit.emotiv.Emotiv     object at 0x7f3206543810>>> failed with TypeError

lsusb output: 
 `Bus 003 Device 006: ID 1234:ed02 Brain Actuated Technologies Emotiv EPOC Developer Headset Wireless Dongle`

dmesg output:

    [20494.658070] usb 3-1: new full-speed USB device number 6 using xhci_hcd
    [20494.679106] usb 3-1: New USB device found, idVendor=1234, idProduct=ed02
    [20494.679120] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
    [20494.679122] usb 3-1: Product: Receiver Dongle L01
    [20494.679124] usb 3-1: Manufacturer: Emotiv Systems Pty Ltd
    [20494.679125] usb 3-1: SerialNumber: SN20110425000016
    [20494.681473] hid-generic 0003:1234:ED02.0006: hidraw1: USB HID v1.11 Device [Emotiv Systems Pty Ltd Receiver Dongle L01] on usb-0000:00:14.0-1/input0
    [20494.684135] hid-generic 0003:1234:ED02.0007: hidraw2: USB HID v1.11 Device [Emotiv Systems Pty Ltd Receiver Dongle L01] on usb-0000:00:14.0-1/input1

**Comment by aponxi** [comment]
Thanks to @isovic I am able to confirm that his solution also works on 14.04.

**Comment by dracog71** [comment]
Thanks to @isovic,  as update, it doesn't full work in Raspberry, the modules "Ctype" for C programming cannot be installed, also "Psyco" : 

`"Could not find a version that satisfies the requierements psyco/ctypes"`

But in /python  "example.py" works great with those changes.

Another problem in Raspberry Pi is, when you want to get info from the EPOC it says "NoneType object has no attribute gyroX" 

I know that its becasue "gyroX" return ` 'None' ` 

It's something with "emotiv.py"  when it starts 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/emokit-0.0.1-py2.7.egg/emokit/emotiv.py", line 353, in setup
    self.setupPosix()
  File "/usr/local/lib/python2.7/dist-packages/emokit-0.0.1-py2.7.egg/emokit/emotiv.py", line 456, in setupPosix
    self.serialNum = setup[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
<Greenlet at 0xd3b5d0: <bound method Emotiv.setup of <emokit.emotiv.Emotiv object at 0xc04770>>> failed with TypeError
```

if someone know how to fix it!

**Comment by bschumacher** [comment]
Psyco not required. Pull the latest version @dracog71. Seems like the initial problem was fixed and latest version weakened those requirements so closing.
